controller:
  service:
    enableHttps: false
    external:
      enabled: false
    internal:
      enabled: true
      annotations:
        networking.gke.io/load-balancer-type: "Internal"
        networking.gke.io/internal-load-balancer-allow-global-access: "true"