apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system 
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: envoy-gateway-lb-service
        annotations:
          networking.gke.io/load-balancer-type: "Internal"
          networking.gke.io/internal-load-balancer-allow-global-access: "true"
