apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
resources:
  - release.yaml
  - repository.yaml
  - namespace.yaml
configMapGenerator:
  - name: envoy-gateway-values
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: envoy-gateway
configurations:
  - kustomizeconfig.yaml