name: gcp-tf-destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    environment: gcp
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token:  'write'

    env:
      TF_VAR_terraform_sa_email: ${{ secrets.TERRAFORM_SA_EMAIL }}
      TF_VAR_billing_account_id: ${{ secrets.BILLING_ACCOUNT_ID }}
      TF_VAR_org_id:             ${{ secrets.ORG_ID }}
      TF_VAR_fluxcd_github_pat:  ${{ secrets.FLUXCD_GITHUB_PAT }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account:            ${{ secrets.TERRAFORM_SA_EMAIL }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -destroy -input=false -out=tfdestroy.plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfdestroy.plan